/**
 * D3 — share.
 *
 * The card preview is not a mock-up drawn in React Native. It is an `<Image>`
 * pointed at `/m/[matchId]/square`, which is the actual PNG that gets sent —
 * the same bytes, from the same route, generated by Satori on the server.
 *
 * That matters more than it sounds: a preview drawn separately from the thing
 * it previews is a second implementation that drifts, and the first time it
 * drifts someone shares a card that does not look like what they were shown.
 *
 * The square one, not the 1200×630 that a link preview unfurls into — this
 * screen sends a picture, and a status crops a landscape card to a strip.
 */
import { useState } from 'react';
import { Image, Pressable, ScrollView, Share, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import * as Clipboard from 'expo-clipboard';
import type { MatchResultResponse } from '@open-innings/shared';
import { api } from '../../../../lib/api';
import { MATCH_CARD_ASPECT_RATIO, shareUrls } from '../../../../lib/config';
import { useApiQuery } from '../../../../lib/use-api';
import { AdBar } from '../../../../components/AdBar';
import { MatchTabs } from '../../../../components/MatchTabs';
import { Button, ErrorBanner, Kicker, LoadingScreen } from '../../../../components/ui';

export default function ShareMatch() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const [copied, setCopied] = useState(false);

  const query = useApiQuery<MatchResultResponse>(
    (t, signal) => api.matchSummary(t, id, signal),
    [id],
  );

  if (query.isLoading) return <LoadingScreen />;

  const url = shareUrls.match(id);
  const m = query.data;
  const headline = m?.result ?? m?.title ?? 'Open Innings';

  async function copyLink() {
    await Clipboard.setStringAsync(url);
    setCopied(true);
    // Long enough to read, short enough that it is gone before the next tap.
    setTimeout(() => setCopied(false), 2000);
  }

  async function shareCard() {
    const lines = (m?.innings ?? []).map(
      (i) => `${i.teamName} ${i.runs}-${i.wickets} (${i.overs})`,
    );
    await Share.share({ message: [headline, ...lines, url].join('\n') });
  }

  return (
    <SafeAreaView className="bg-background flex-1">
      <Stack.Screen options={{ headerShown: false }} />

      <View className="flex-row items-center gap-2 px-3 pb-2 pt-3">
        <Pressable
          accessibilityRole="button"
          accessibilityLabel="Back"
          onPress={() => router.back()}
          className="h-9 w-8 items-center justify-center active:opacity-60"
        >
          <Text className="text-foreground/70 text-xl">‹</Text>
        </Pressable>
        <Text className="text-foreground font-heading min-w-0 flex-1 text-[19px]">Share</Text>
        <Text className="font-heading shrink-0 text-[9px] uppercase tracking-[1.3px] text-neutral-500">
          1080 × 1080
        </Text>
      </View>

      <ScrollView contentContainerClassName="px-4 pb-4">
        {query.error ? <ErrorBanner message={query.error} /> : null}

        {/* The real card, at the ratio it is actually generated at. */}
        <View className="border-border border">
          <Image
            source={{ uri: shareUrls.matchCardImage(id) }}
            style={{ width: '100%', aspectRatio: MATCH_CARD_ASPECT_RATIO }}
            resizeMode="contain"
            accessibilityLabel={`Share card: ${headline}`}
          />
        </View>

        <View className="mt-4 flex-row gap-2">
          <View className="flex-1">
            <Button
              label={copied ? 'Link copied' : 'Copy live link'}
              variant="secondary"
              onPress={() => void copyLink()}
            />
          </View>
          <View className="flex-1">
            <Button
              label="Player cards"
              variant="secondary"
              onPress={() => router.push({ pathname: '/matches/[id]/cards', params: { id } })}
            />
          </View>
        </View>

        <View className="mt-2">
          {/*
            The system sheet, not a WhatsApp deep link. WhatsApp is where this
            is going and it sits first in that sheet anyway — but hard-wiring
            `whatsapp://` fails silently on a phone without it, and excludes
            everyone who shares to Telegram or a group email.
          */}
          <Button label="Share the card" onPress={() => void shareCard()} />
        </View>

        <View className="border-border mt-5 border-t pt-3">
          <Kicker>What gets sent</Kicker>
          <Text className="text-foreground/60 mt-1.5 text-[12px] leading-[18px]">
            The link opens the live scorecard — it keeps updating while the match is on, and it
            never expires. The image is a snapshot of the score right now.
          </Text>
          {/*
            The design promises "Free plan adds a small Open Innings footer to
            shared images". The card renderer does not brand differently by
            plan — there are no plans yet — so that is not claimed here.
          */}
        </View>
      </ScrollView>

      <AdBar />
      <MatchTabs matchId={id} active="card" />
    </SafeAreaView>
  );
}
