/**
 * Zod schemas for every API input.
 *
 * One definition, two consumers: route handlers validate incoming JSON with
 * these, and the mobile client builds request bodies from the inferred types.
 * A field renamed here breaks compilation on both sides at once, which is the
 * entire point — a REST boundary is exactly where client and server silently
 * drift apart.
 *
 * Error messages here are user-facing. They surface directly in form errors
 * on web and in toasts on mobile, so write them for a person, not a log.
 */
import { z } from 'zod';
import {
  BATTING_STYLES,
  BOWLING_STYLES,
  PLAYER_ROLES,
  TOSS_DECISIONS,
  BALL_EVENT_TYPES,
  WICKET_TYPES,
} from './enums';

/**
 * Deliberately permissive: anything with an `@` and no whitespace.
 *
 * `z.string().email()` rejects the single-label hostnames used by dev seeds
 * and local fixtures. Real deliverability is proven by sending mail, not by
 * a regex, so a stricter pattern here would buy nothing and break seeding.
 */
export const emailSchema = z
  .string()
  .trim()
  .toLowerCase()
  .min(3, 'Enter a valid email')
  .regex(/^[^@\s]+@[^@\s]+$/, 'Enter a valid email');

/** A database id. Not `.uuid()` — ids are generated by nanoid, not Postgres. */
const idSchema = z.string().trim().min(1);

/** Optional free text: blank strings collapse to undefined so the DB stores NULL. */
const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .optional()
    .transform((v) => (v === '' ? undefined : v));

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

export const signupSchema = z.object({
  email: emailSchema,
  password: z.string().min(8, 'Password must be at least 8 characters'),
  displayName: z.string().trim().min(1).max(80).optional(),
});
export type SignupInput = z.infer<typeof signupSchema>;

export const loginSchema = z.object({
  email: emailSchema,
  password: z.string().min(1, 'Password is required'),
});
export type LoginInput = z.infer<typeof loginSchema>;

// ---------------------------------------------------------------------------
// Players
// ---------------------------------------------------------------------------

export const createPlayerSchema = z.object({
  fullName: z.string().trim().min(1, 'Full name is required').max(120),
  shortName: optionalText(40),
  battingStyle: z.enum(BATTING_STYLES).optional(),
  bowlingStyle: z.enum(BOWLING_STYLES).optional(),
  role: z.enum(PLAYER_ROLES).optional(),
});
export type CreatePlayerInput = z.infer<typeof createPlayerSchema>;

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export const createTeamSchema = z.object({
  name: z.string().trim().min(1, 'Team name is required').max(80),
  shortName: optionalText(16),
  homeGround: optionalText(120),
});
export type CreateTeamInput = z.infer<typeof createTeamSchema>;

export const updateTeamSchema = createTeamSchema;
export type UpdateTeamInput = z.infer<typeof updateTeamSchema>;

export const teamMemberSchema = z.object({
  playerId: idSchema,
});
export type TeamMemberInput = z.infer<typeof teamMemberSchema>;

// ---------------------------------------------------------------------------
// Matches
// ---------------------------------------------------------------------------

/**
 * The three opening players every innings needs.
 *
 * Squad membership is *not* checked here — that needs a database round trip,
 * so the route handler re-verifies it. Schemas prove shape, not authority.
 */
export const openersSchema = z
  .object({
    openingStrikerId: idSchema,
    openingNonStrikerId: idSchema,
    openingBowlerId: idSchema,
  })
  .refine((v) => v.openingStrikerId !== v.openingNonStrikerId, {
    message: 'Striker and non-striker must be different players',
    path: ['openingNonStrikerId'],
  });
export type OpenersInput = z.infer<typeof openersSchema>;

export const createMatchSchema = z
  .object({
    title: optionalText(120),
    venue: optionalText(120),
    oversPerInnings: z.coerce
      .number()
      .int('Overs must be a whole number')
      .min(1, 'Overs must be a positive number')
      .max(200),
    teamAId: idSchema,
    teamBId: idSchema,
    tossWinnerTeamId: idSchema.optional(),
    tossDecision: z.enum(TOSS_DECISIONS).optional(),
    openingStrikerId: idSchema,
    openingNonStrikerId: idSchema,
    openingBowlerId: idSchema,
  })
  .refine((v) => v.teamAId !== v.teamBId, {
    message: 'Pick two different teams',
    path: ['teamBId'],
  })
  .refine((v) => v.openingStrikerId !== v.openingNonStrikerId, {
    message: 'Striker and non-striker must be different players',
    path: ['openingNonStrikerId'],
  })
  .refine(
    // A toss is all-or-nothing: a winner without a decision tells us nothing
    // about who bats, and silently defaulting would put the wrong side in.
    (v) => (v.tossWinnerTeamId === undefined) === (v.tossDecision === undefined),
    { message: 'Record both the toss winner and their decision', path: ['tossDecision'] },
  )
  .refine(
    (v) =>
      v.tossWinnerTeamId === undefined ||
      v.tossWinnerTeamId === v.teamAId ||
      v.tossWinnerTeamId === v.teamBId,
    { message: 'The toss winner must be one of the two teams', path: ['tossWinnerTeamId'] },
  );
export type CreateMatchInput = z.infer<typeof createMatchSchema>;

/** Innings 2 needs openers only — sides and target are derived from innings 1. */
export const startSecondInningsSchema = openersSchema;
export type StartSecondInningsInput = z.infer<typeof startSecondInningsSchema>;

// ---------------------------------------------------------------------------
// Ball events
// ---------------------------------------------------------------------------

/**
 * A single delivery, as the scorer UI reports it.
 *
 * This validates *shape* only. Legality — whether this bowler may bowl this
 * over, whether that batter is even in — is the scoring engine's job, and it
 * throws `ScoringError` for anything it rejects. Do not duplicate rules here;
 * the engine is the single source of truth for cricket law.
 */
export const ballEventSchema = z.object({
  type: z.enum(BALL_EVENT_TYPES),
  runs: z.coerce.number().int().min(0).max(12).optional(),
  isWicket: z.boolean().optional(),
  wicketType: z.enum(WICKET_TYPES).optional(),
  dismissedPlayerId: idSchema.optional(),
  fielderId: idSchema.optional(),
  strikerId: idSchema.optional(),
  nonStrikerId: idSchema.optional(),
  bowlerId: idSchema.optional(),
  commentary: optionalText(280),
});
export type BallEventBody = z.infer<typeof ballEventSchema>;

/** The bowler taking the next over, sent when the scorer closes an over. */
export const changeBowlerSchema = z.object({
  bowlerId: idSchema,
});
export type ChangeBowlerInput = z.infer<typeof changeBowlerSchema>;

/** The batter walking in after a wicket, and which end they take. */
export const nextBatterSchema = z.object({
  playerId: idSchema,
  slot: z.enum(['striker', 'non_striker']),
});
export type NextBatterInput = z.infer<typeof nextBatterSchema>;
