/**
 * Zod schemas for every API input.
 *
 * One definition, two consumers: route handlers validate incoming JSON with
 * these, and the mobile client builds request bodies from the inferred types.
 * A field renamed here breaks compilation on both sides at once, which is the
 * entire point — a REST boundary is exactly where client and server silently
 * drift apart.
 *
 * Error messages here are user-facing. They surface directly in form errors
 * on web and in toasts on mobile, so write them for a person, not a log.
 */
import { z } from 'zod';
import {
  BATTING_STYLES,
  BOWLING_STYLES,
  PLAYER_ROLES,
  MATCH_FORMATS,
  TOSS_DECISIONS,
  BALL_EVENT_TYPES,
  WICKET_TYPES,
} from './enums';

/**
 * Deliberately permissive: anything with an `@` and no whitespace.
 *
 * `z.string().email()` rejects the single-label hostnames used by dev seeds
 * and local fixtures. Real deliverability is proven by sending mail, not by
 * a regex, so a stricter pattern here would buy nothing and break seeding.
 */
export const emailSchema = z
  .string()
  .trim()
  .toLowerCase()
  .min(3, 'Enter a valid email')
  .regex(/^[^@\s]+@[^@\s]+$/, 'Enter a valid email');

/** A database id. Not `.uuid()` — ids are generated by nanoid, not Postgres. */
const idSchema = z.string().trim().min(1);

/** Optional free text: blank strings collapse to undefined so the DB stores NULL. */
const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .optional()
    .transform((v) => (v === '' ? undefined : v));

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

export const signupSchema = z.object({
  email: emailSchema,
  password: z.string().min(8, 'Password must be at least 8 characters'),
  displayName: z.string().trim().min(1).max(80).optional(),
});
export type SignupInput = z.infer<typeof signupSchema>;

export const loginSchema = z.object({
  email: emailSchema,
  password: z.string().min(1, 'Password is required'),
});
export type LoginInput = z.infer<typeof loginSchema>;

// ---------------------------------------------------------------------------
// Players
// ---------------------------------------------------------------------------

export const createPlayerSchema = z.object({
  fullName: z.string().trim().min(1, 'Full name is required').max(120),
  shortName: optionalText(40),
  battingStyle: z.enum(BATTING_STYLES).optional(),
  bowlingStyle: z.enum(BOWLING_STYLES).optional(),
  role: z.enum(PLAYER_ROLES).optional(),
});
export type CreatePlayerInput = z.infer<typeof createPlayerSchema>;

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export const createTeamSchema = z.object({
  name: z.string().trim().min(1, 'Team name is required').max(80),
  shortName: optionalText(16),
  homeGround: optionalText(120),
});
export type CreateTeamInput = z.infer<typeof createTeamSchema>;

export const updateTeamSchema = createTeamSchema;
export type UpdateTeamInput = z.infer<typeof updateTeamSchema>;

export const teamMemberSchema = z.object({
  playerId: idSchema,
});
export type TeamMemberInput = z.infer<typeof teamMemberSchema>;

// ---------------------------------------------------------------------------
// Matches
// ---------------------------------------------------------------------------

/**
 * The three opening players every innings needs.
 *
 * Squad membership is *not* checked here — that needs a database round trip,
 * so the route handler re-verifies it. Schemas prove shape, not authority.
 */
export const openersSchema = z
  .object({
    openingStrikerId: idSchema,
    openingNonStrikerId: idSchema,
    openingBowlerId: idSchema,
  })
  .refine((v) => v.openingStrikerId !== v.openingNonStrikerId, {
    message: 'Striker and non-striker must be different players',
    path: ['openingNonStrikerId'],
  });
export type OpenersInput = z.infer<typeof openersSchema>;

export const createMatchSchema = z
  .object({
    title: optionalText(120),
    venue: optionalText(120),
    oversPerInnings: z.coerce
      .number()
      .int('Overs must be a whole number')
      .min(1, 'Overs must be a positive number')
      .max(200),
    /** A label the match wears. Optional — an unlabelled match still scores. */
    format: z.enum(MATCH_FORMATS).optional(),
    teamAId: idSchema,
    teamBId: idSchema,
    tossWinnerTeamId: idSchema.optional(),
    tossDecision: z.enum(TOSS_DECISIONS).optional(),
    openingStrikerId: idSchema,
    openingNonStrikerId: idSchema,
    openingBowlerId: idSchema,
  })
  .refine((v) => v.teamAId !== v.teamBId, {
    message: 'Pick two different teams',
    path: ['teamBId'],
  })
  .refine((v) => v.openingStrikerId !== v.openingNonStrikerId, {
    message: 'Striker and non-striker must be different players',
    path: ['openingNonStrikerId'],
  })
  .refine(
    // A toss is all-or-nothing: a winner without a decision tells us nothing
    // about who bats, and silently defaulting would put the wrong side in.
    (v) => (v.tossWinnerTeamId === undefined) === (v.tossDecision === undefined),
    { message: 'Record both the toss winner and their decision', path: ['tossDecision'] },
  )
  .refine(
    (v) =>
      v.tossWinnerTeamId === undefined ||
      v.tossWinnerTeamId === v.teamAId ||
      v.tossWinnerTeamId === v.teamBId,
    { message: 'The toss winner must be one of the two teams', path: ['tossWinnerTeamId'] },
  );
export type CreateMatchInput = z.infer<typeof createMatchSchema>;

/** Innings 2 needs openers only — sides and target are derived from innings 1. */
export const startSecondInningsSchema = openersSchema;
export type StartSecondInningsInput = z.infer<typeof startSecondInningsSchema>;

// ---------------------------------------------------------------------------
// Ball events
// ---------------------------------------------------------------------------

/**
 * A single delivery, exactly as the scorer sends it.
 *
 * This is the wire shape of `BallEventInput` from @open-innings/scoring, and
 * it had to be rewritten: the previous version described a request nobody
 * makes — `{ type, runs, isWicket }` — and was never imported anywhere, so the
 * ball endpoint had been casting raw JSON with `as BallEventInput` since it
 * was written. A schema that does not match the traffic is worse than none,
 * because it reads like a guarantee.
 *
 * Shape only. Whether this bowler may bowl this over, and whether that batter
 * is even in, are the engine's business — it throws `ScoringError` for
 * anything it rejects. Do not restate cricket law here.
 *
 * ## What is deliberately absent
 *
 * `isFreeHit`, `isLegalDelivery`, `totalRuns` and `id` are **not** accepted.
 * Zod strips unknown keys, so a client sending them is ignored rather than
 * refused, and the engine derives all four itself. That is not tidiness:
 *
 *   - `isFreeHit: false` on the ball after a no-ball would let a client
 *     record a bowled dismissal that Law 21.18 forbids;
 *   - `isLegalDelivery: false` on a normal delivery would stop the over ever
 *     advancing;
 *   - a `totalRuns` disagreeing with its own parts would put any number on
 *     the board.
 *
 * Every one of those was reachable while the endpoint cast instead of parsed.
 */
export const ballEventSchema = z.object({
  /** Ignored by the server, which uses the innings the match is actually on. */
  inningsId: idSchema.optional(),

  eventType: z.enum(BALL_EVENT_TYPES),
  /**
   * Off the bat, 0..6.
   *
   * `z.number()` and not `z.coerce.number()`. Coercion runs `Number()`, which
   * turns `null` into 0, `true` into 1, `[]` into 0 and `[4]` into 4 — so a
   * malformed body would have recorded a wrong delivery with a 200 instead of
   * being refused, which is the exact failure this schema was wired up to
   * stop. Every caller (the app and all three smoke scripts) sends real
   * numbers, so there is nothing to coerce.
   */
  runsOffBat: z.number().int().min(0).max(6),
  /** Penalties plus byes. Well above anything real, but bounded. */
  extraRuns: z.number().int().min(0).max(12),

  batsmanId: idSchema,
  nonStrikerId: idSchema,
  bowlerId: idSchema,

  wicketType: z.enum(WICKET_TYPES).optional(),
  wicketPlayerId: idSchema.optional(),
  fielderId: idSchema.optional(),

  commentary: optionalText(280),
});
export type BallEventBody = z.infer<typeof ballEventSchema>;

/**
 * The event type and the runs have to describe the same delivery.
 *
 * Shape alone let `{ eventType: 'wide', runsOffBat: 6 }` and
 * `{ eventType: '6', runsOffBat: 0 }` both through. Neither is a delivery
 * that can happen, and both persist happily — leaving the ball chip on the
 * card saying one thing and the score saying another, with no error anywhere
 * to explain it.
 *
 * This is not cricket law, which stays in the engine. It is the narrower
 * claim that a payload must be internally consistent before anyone reasons
 * about it.
 */
const RUNS_FOR_TYPE: Partial<Record<(typeof BALL_EVENT_TYPES)[number], number>> = {
  dot: 0,
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
  '5': 5,
  '6': 6,
};

/** Types that carry a penalty or come off something other than the bat. */
const EXTRA_TYPES = new Set(['wide', 'no_ball', 'bye', 'leg_bye']);

export const consistentBallEventSchema = ballEventSchema.superRefine((v, ctx) => {
  const expected = RUNS_FOR_TYPE[v.eventType];

  // A scoring shot names its own runs, and carries no extras.
  if (expected !== undefined) {
    if (v.runsOffBat !== expected) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['runsOffBat'],
        message: `A '${v.eventType}' is ${expected} off the bat, not ${v.runsOffBat}`,
      });
    }
    if (v.extraRuns !== 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['extraRuns'],
        message: `A '${v.eventType}' carries no extras`,
      });
    }
    return;
  }

  if (EXTRA_TYPES.has(v.eventType)) {
    // Every one of these puts at least one run on the board: a penalty for a
    // wide or no-ball, and a completed run for a bye or leg-bye.
    if (v.extraRuns < 1) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['extraRuns'],
        message: `A '${v.eventType}' scores at least one extra`,
      });
    }
    // Only a no-ball can be struck; the others never touched the bat.
    if (v.eventType !== 'no_ball' && v.runsOffBat !== 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['runsOffBat'],
        message: `A '${v.eventType}' is never off the bat`,
      });
    }
  }

  // 'wicket' is left alone: a run-out can happen after any number of runs.
});

/** The bowler taking the next over, sent when the scorer closes an over. */
export const changeBowlerSchema = z.object({
  bowlerId: idSchema,
});
export type ChangeBowlerInput = z.infer<typeof changeBowlerSchema>;

/** The batter walking in after a wicket, and which end they take. */
export const nextBatterSchema = z.object({
  playerId: idSchema,
  slot: z.enum(['striker', 'non_striker']),
});
export type NextBatterInput = z.infer<typeof nextBatterSchema>;
